#include "gemms.h"

#ifdef ARM32
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void optkern
   (const int M, const int N, const int K, const double alpha, 
    const double * ATL_RESTRICT A, const int lda, 
    const double * ATL_RESTRICT B, const int ldb, 
    const double beta, double * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=0, 
 * lda=0, ldb=0, ldc=0, mu=5, nu=4, ku=1, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.11.30)
 */
{
   const int Mb = (M/5)*5;
   const int Nb = (N>>2)<<2;
   #define Kb K
   const double *stM = A + (lda*Mb);
   const double *stN = B + (ldb*Nb);
   #define incAk 1
   const int incAm = ((((lda) << 2)+lda) - Kb), incAn = -(Mb*lda);
   #define incBk 1
   const int incBm = -(Kb), incBn = (((ldb) << 2));
   #define incCm 5
   const int incCn = (((ldc) << 2)) - (Mb);
   double *pC0=C, *pC1=pC0+(ldc), *pC2=pC1+(ldc), *pC3=pC2+(ldc);
   const double *pA0=A, *pA1=pA0+(lda), *pA2=pA1+(lda), *pA3=pA2+(lda), *pA4=pA3+(lda);
   const double *pB0=B, *pB1=pB0+(ldb), *pB2=pB1+(ldb), *pB3=pB2+(ldb);
   register int k;
   register double rA0, rA1, rA2, rA3, rA4;
   register double rB0, rB1, rB2, rB3;
   register double rC0_0, rC1_0, rC2_0, rC3_0, rC4_0, rC0_1, rC1_1, rC2_1, rC3_1, rC4_1, rC0_2, rC1_2, rC2_2, rC3_2, rC4_2, rC0_3, rC1_3, rC2_3, rC3_3, rC4_3;
   do /* N-loop */
   {
      do /* M-loop */
      {
         rC0_0 = *pC0;
         rC1_0 = pC0[1];
         rC2_0 = pC0[2];
         rC3_0 = pC0[3];
         rC4_0 = pC0[4];
         rC0_1 = *pC1;
         rC1_1 = pC1[1];
         rC2_1 = pC1[2];
         rC3_1 = pC1[3];
         rC4_1 = pC1[4];
         rC0_2 = *pC2;
         rC1_2 = pC2[1];
         rC2_2 = pC2[2];
         rC3_2 = pC2[3];
         rC4_2 = pC2[4];
         rC0_3 = *pC3;
         rC1_3 = pC3[1];
         rC2_3 = pC3[2];
         rC3_3 = pC3[3];
         rC4_3 = pC3[4];
         for (k=K; k; k--) /* easy loop to unroll */
         {
            rA0 = *pA0;
            rB0 = *pB0;
            rA1 = *pA1;
            rA2 = *pA2;
            rA3 = *pA3;
            rA4 = *pA4;
            rB1 = *pB1;
            rB2 = *pB2;
            rB3 = *pB3;
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            rC3_0 += rA3 * rB0;
            rC4_0 += rA4 * rB0;
            rC0_1 += rA0 * rB1;
            rC1_1 += rA1 * rB1;
            rC2_1 += rA2 * rB1;
            rC3_1 += rA3 * rB1;
            rC4_1 += rA4 * rB1;
            rC0_2 += rA0 * rB2;
            rC1_2 += rA1 * rB2;
            rC2_2 += rA2 * rB2;
            rC3_2 += rA3 * rB2;
            rC4_2 += rA4 * rB2;
            rC0_3 += rA0 * rB3;
            rC1_3 += rA1 * rB3;
            rC2_3 += rA2 * rB3;
            rC3_3 += rA3 * rB3;
            rC4_3 += rA4 * rB3;
            pA0 += incAk;
            pA1 += incAk;
            pA2 += incAk;
            pA3 += incAk;
            pA4 += incAk;
            pB0 += incBk;
            pB1 += incBk;
            pB2 += incBk;
            pB3 += incBk;
         }
         *pC0 = rC0_0;
         pC0[1] = rC1_0;
         pC0[2] = rC2_0;
         pC0[3] = rC3_0;
         pC0[4] = rC4_0;
         *pC1 = rC0_1;
         pC1[1] = rC1_1;
         pC1[2] = rC2_1;
         pC1[3] = rC3_1;
         pC1[4] = rC4_1;
         *pC2 = rC0_2;
         pC2[1] = rC1_2;
         pC2[2] = rC2_2;
         pC2[3] = rC3_2;
         pC2[4] = rC4_2;
         *pC3 = rC0_3;
         pC3[1] = rC1_3;
         pC3[2] = rC2_3;
         pC3[3] = rC3_3;
         pC3[4] = rC4_3;
         pC0 += incCm;
         pC1 += incCm;
         pC2 += incCm;
         pC3 += incCm;
         pA0 += incAm;
         pA1 += incAm;
         pA2 += incAm;
         pA3 += incAm;
         pA4 += incAm;
         pB0 += incBm;
         pB1 += incBm;
         pB2 += incBm;
         pB3 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pC1 += incCn;
      pC2 += incCn;
      pC3 += incCn;
      pA0 += incAn;
      pA1 += incAn;
      pA2 += incAn;
      pA3 += incAn;
      pA4 += incAn;
      pB0 += incBn;
      pB1 += incBn;
      pB2 += incBn;
      pB3 += incBn;
   }
   while(pB0 != stN);
}
#undef ATL_RESTRICT
#undef Kb
#undef incAk
#undef incBk
#undef incCm

#elif defined(SPARC)

static void optkern(const int M, const int N, const int K, const double alpha,
                    const double *A, const int lda, const double *B, 
                    const int ldb, const double beta, double *C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=0, 
 * lda=0, ldb=0, ldc=0, mu=4, nu=4, ku=1
 */
{
   const int Mb = (M>>2)<<2;
   const int Nb = (N>>2)<<2;
   #define Kb K
   const int Kloop = K - 1;
   const double *stM = A + (lda*Mb);
   const double *stN = B + (ldb*Nb);
   #define incAk 1
   const int incAm = ((((lda) << 2)) - Kb), incAn = -(Mb*lda);
   #define incBk 1
   const int incBm = -(Kb), incBn = (((ldb) << 2));
   #define incAk0 incAk
   #define incBk0 incBk
   #define incCm 4
   const int incCn = (((ldc) << 2)) - (Mb);
   double *pC0=C, *pC1=pC0+(ldc), *pC2=pC1+(ldc), *pC3=pC2+(ldc);
   const double *pA0=A, *pA1=pA0+(lda), *pA2=pA1+(lda), *pA3=pA2+(lda);
   const double *pB0=B, *pB1=pB0+(ldb), *pB2=pB1+(ldb), *pB3=pB2+(ldb);
   register int k;
   register double rA0, rA1, rA2, rA3;
   register double rB0, rB1, rB2, rB3;
   register double m0, m1, m2, m3;
   register double rC0_0, rC1_0, rC2_0, rC3_0, rC0_1, rC1_1, rC2_1, rC3_1, 
                   rC0_2, rC1_2, rC2_2, rC3_2, rC0_3, rC1_3, rC2_3, rC3_3;
   do /* N-loop */
   {
      do /* M-loop */
      {
         #if defined(BETA0) || !defined(ALPHA1)
           rC0_0 = rC1_0 = rC2_0 = rC3_0 = 
           rC0_1 = rC1_1 = rC2_1 = rC3_1 = 
           rC0_2 = rC1_2 = rC2_2 = rC3_2 = 
           rC0_3 = rC1_3 = rC2_3 = rC3_3 = 0.0;
         #else
            rC0_0 = *pC0; rC1_0 = pC0[1]; rC2_0 = pC0[2]; rC3_0 = pC0[3];
            rC0_1 = *pC1; rC1_1 = pC1[1]; rC2_1 = pC1[2]; rC3_1 = pC1[3];
            rC0_2 = *pC2; rC1_2 = pC2[1]; rC2_2 = pC2[2]; rC3_2 = pC2[3];
            rC0_3 = *pC3; rC1_3 = pC3[1]; rC2_3 = pC3[2]; rC3_3 = pC3[3];
            #ifdef BETAX
               rC0_0 *= beta; rC1_0 *= beta; rC2_0 *= beta; rC3_0 *= beta;
               rC0_1 *= beta; rC1_1 *= beta; rC2_1 *= beta; rC3_1 *= beta;
               rC0_2 *= beta; rC1_2 *= beta; rC2_2 *= beta; rC3_2 *= beta;
               rC0_3 *= beta; rC1_3 *= beta; rC2_3 *= beta; rC3_3 *= beta;
            #endif
         #endif
/*
 *       Start pipeline
 */
         rA0 = *pA0;
         rB0 = *pB0;
         rA1 = *pA1;
         rA2 = *pA2;
         rA3 = *pA3;
         rB1 = *pB1;
         rB2 = *pB2;
         rB3 = *pB3;
         m0 = rA0 * rB0;
         m1 = rA1 * rB0;
         m2 = rA2 * rB0;
         m3 = rA3 * rB0;

         for (k=Kloop; k; k--) /* easy loop to unroll */
         {
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC1_0 += m1;
            m1 = rA1 * rB1;
            rC2_0 += m2;
            m2 = rA2 * rB1;
            rC3_0 += m3;
            m3 = rA3 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC1_1 += m1;
            m1 = rA1 * rB2;
            rC2_1 += m2;
            m2 = rA2 * rB2;
            rC3_1 += m3;
            m3 = rA3 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC1_2 += m1;
            m1 = rA1 * rB3;
            rC2_2 += m2;
            m2 = rA2 * rB3;
            rC3_2 += m3;
            m3 = rA3 * rB3;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rA1 = pA1[1];
            rA2 = pA2[1];
            rA3 = pA3[1];
            rB1 = pB1[1];
            rB2 = pB2[1];
            rB3 = pB3[1];
            rC0_3 += m0;
            m0 = rA0 * rB0;
            rC1_3 += m1;
            m1 = rA1 * rB0;
            rC2_3 += m2;
            m2 = rA2 * rB0;
            rC3_3 += m3;
            m3 = rA3 * rB0;
            pA0 += incAk;
            pA1 += incAk;
            pA2 += incAk;
            pA3 += incAk;
            pB0 += incBk;
            pB1 += incBk;
            pB2 += incBk;
            pB3 += incBk;
         }
/*
 *       Drain pipe on last iteration of K-loop
 */
         rC0_0 += m0;
         m0 = rA0 * rB1;
         rC1_0 += m1;
         m1 = rA1 * rB1;
         rC2_0 += m2;
         m2 = rA2 * rB1;
         rC3_0 += m3;
         m3 = rA3 * rB1;
         rC0_1 += m0;
         m0 = rA0 * rB2;
         rC1_1 += m1;
         m1 = rA1 * rB2;
         rC2_1 += m2;
         m2 = rA2 * rB2;
         rC3_1 += m3;
         m3 = rA3 * rB2;
         rC0_2 += m0;
         m0 = rA0 * rB3;
         rC1_2 += m1;
         m1 = rA1 * rB3;
         rC2_2 += m2;
         m2 = rA2 * rB3;
         rC3_2 += m3;
         m3 = rA3 * rB3;
         rC0_3 += m0;
         rC1_3 += m1;
         rC2_3 += m2;
         rC3_3 += m3;
         pA0 += incAk0;
         pA1 += incAk0;
         pA2 += incAk0;
         pA3 += incAk0;
         pB0 += incBk0;
         pB1 += incBk0;
         pB2 += incBk0;
         pB3 += incBk0;
         #if !defined(ALPHA1)
            rC0_0 *= alpha; rC1_0 *= alpha; rC2_0 *= alpha; rC3_0 *= alpha;
            rC0_1 *= alpha; rC1_1 *= alpha; rC2_1 *= alpha; rC3_1 *= alpha;
            rC0_2 *= alpha; rC1_2 *= alpha; rC2_2 *= alpha; rC3_2 *= alpha;
            rC0_3 *= alpha; rC1_3 *= alpha; rC2_3 *= alpha; rC3_3 *= alpha;
            #ifdef BETA0
               *pC0 = rC0_0; pC0[1] = rC1_0; pC0[2] = rC2_0; pC0[3] = rC3_0;
               *pC1 = rC0_1; pC1[1] = rC1_1; pC1[2] = rC2_1; pC1[3] = rC3_1;
               *pC2 = rC0_2; pC2[1] = rC1_2; pC2[2] = rC2_2; pC2[3] = rC3_2;
               *pC3 = rC0_3; pC3[1] = rC1_3; pC3[2] = rC2_3; pC3[3] = rC3_3;
            #elif defined(BETA1)
               *pC0 += rC0_0; pC0[1] += rC1_0; pC0[2] += rC2_0; pC0[3] += rC3_0;
               *pC1 += rC0_1; pC1[1] += rC1_1; pC1[2] += rC2_1; pC1[3] += rC3_1;
               *pC2 += rC0_2; pC2[1] += rC1_2; pC2[2] += rC2_2; pC2[3] += rC3_2;
               *pC3 += rC0_3; pC3[1] += rC1_3; pC3[2] += rC2_3; pC3[3] += rC3_3;
            #else
               *pC0   = rC0_0 + beta * *pC0;
               pC0[1] = rC1_0 + beta * pC0[1];
               pC0[2] = rC2_0 + beta * pC0[2];
               pC0[3] = rC3_0 + beta * pC0[3];
               *pC1   = rC0_1 + beta * *pC1;
               pC1[1] = rC1_1 + beta * pC1[1];
               pC1[2] = rC2_1 + beta * pC1[2];
               pC1[3] = rC3_1 + beta * pC1[3];
               *pC2   = rC0_2 + beta * *pC2;
               pC2[1] = rC1_2 + beta * pC2[1];
               pC2[2] = rC2_2 + beta * pC2[2];
               pC2[3] = rC3_2 + beta * pC2[3];
               *pC3   = rC0_3 + beta * *pC3;
               pC3[1] = rC1_3 + beta * pC3[1];
               pC3[2] = rC2_3 + beta * pC3[2];
               pC3[3] = rC3_3 + beta * pC3[3];
            #endif
         #else
            *pC0 = rC0_0; pC0[1] = rC1_0; pC0[2] = rC2_0; pC0[3] = rC3_0;
            *pC1 = rC0_1; pC1[1] = rC1_1; pC1[2] = rC2_1; pC1[3] = rC3_1;
            *pC2 = rC0_2; pC2[1] = rC1_2; pC2[2] = rC2_2; pC2[3] = rC3_2;
            *pC3 = rC0_3; pC3[1] = rC1_3; pC3[2] = rC2_3; pC3[3] = rC3_3;
         #endif
         pC0 += incCm;
         pC1 += incCm;
         pC2 += incCm;
         pC3 += incCm;
         pA0 += incAm;
         pA1 += incAm;
         pA2 += incAm;
         pA3 += incAm;
         pB0 += incBm;
         pB1 += incBm;
         pB2 += incBm;
         pB3 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pC1 += incCn;
      pC2 += incCn;
      pC3 += incCn;
      pA0 += incAn;
      pA1 += incAn;
      pA2 += incAn;
      pA3 += incAn;
      pB0 += incBn;
      pB1 += incBn;
      pB2 += incBn;
      pB3 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAk
   #undef incAk
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef Kb
   #undef Kb
#endif

#else

static void optkern(const int M, const int N, const int K, const double alpha,
                    const double *A, const int lda, const double *B, 
                    const int ldb, const double beta, double *C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=0, 
 * lda=0, ldb=0, ldc=0, mu=2, nu=1, ku=1
 */
{
   const int Mb = (M>>1)<<1;
   #define Nb N
   #define Kb K
   const double *stM = A + (lda*Mb);
   const double *stN = B + (ldb*Nb);
   #define incAk 1
   const int incAm = ((((lda) << 1)) - Kb), incAn = -(Mb*lda);
   #define incBk 1
   const int incBm = -(Kb), incBn = (ldb);
   #define incCm 2
   const int incCn = (ldc) - (Mb);
   double *pC0=C;
   const double *pA0=A, *pA1=pA0+(lda);
   const double *pB0=B;
   register int k;
   register double rA0, rA1;
   register double rB0;
   register double rC0_0, rC1_0;
   do /* N-loop */
   {
      do /* M-loop */
      {
         #if defined(BETA0) || !defined(ALPHA1)
            rC0_0 = rC1_0 = 0.0;
         #elif defined(BETA1)
            rC0_0 = *pC0;
            rC1_0 = pC0[1];
         #else
            rC0_0 = *pC0 * beta;
            rC1_0 = pC0[1] * beta;
         #endif
         for (k=K; k; k--) /* easy loop to unroll */
         {
            rA0 = *pA0;
            rB0 = *pB0;
            rA1 = *pA1;
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            pA0 += incAk;
            pA1 += incAk;
            pB0 += incBk;
         }
         #if !defined(ALPHA1)
            rC0_0 *= alpha;
            rC1_0 *= alpha;
            #ifdef BETA0
               *pC0 = rC0_0;
               pC0[1] = rC1_0;
            #elif defined(BETA1)
               *pC0 += rC0_0;
               pC0[1] += rC1_0;
            #else
               *pC0 = *pC0 * beta + rC0_0;
               pC0[1] = pC0[1] * beta + rC1_0;
            #endif
         #else
            *pC0 = rC0_0;
            pC0[1] = rC1_0;
         #endif
         pC0 += incCm;
         pA0 += incAm;
         pA1 += incAm;
         pB0 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pA0 += incAn;
      pA1 += incAn;
      pB0 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAk
   #undef incAk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif

#endif

#ifdef BETA1
   #ifdef ALPHA1
void dgemm_a1b1
   #else
void dgemm_aXb1
   #endif
#elif defined(BETA0)
   #ifdef ALPHA1
void dgemm_a1b0
   #else
void dgemm_aXb0
   #endif
#else
   #ifdef ALPHA1
void dgemm_a1bX
   #else
void dgemm_aXbX
   #endif
#endif
   (int ta, int tb, int M, int N, int K, double alpha, const double *A,
    int lda, const double *B, int ldb, const double beta, double *C, int ldc)
{
   int i, j, k;
   register double c00;

#ifdef SPARC
   if (!((M&3) | (N&3)))
#elif defined(ARM32)
   if (!(N&3) && (M/5*5 == M))
#else
   if (!(M&1))
#endif
   {
      optkern(M, N, K, alpha, A, lda, B, ldb, beta, C, ldc);
      return;
   }
   for (j=0; j < N; j++)
   {
      for (i=0; i < M; i++)
      {
         #if defined(BETA0) || !defined(ALPHA1)
            c00 = 0.0;
         #elif defined(BETA1)
            c00 = C[i+j*ldc];
         #else
            c00 = C[i+j*ldc] * beta;
         #endif
         for (k=0; k < K; k++)
         {
            c00 += A[k+i*lda] * B[k+j*ldb];
         }
         #if !defined(ALPHA1)
            c00 *= alpha;
            #ifdef BETA0
               C[i+j*ldc] = c00;
            #elif defined(BETA1)
               C[i+j*ldc] += c00;
            #else
               C[i+j*ldc] = c00 + C[i+j*ldc]*beta;
            #endif
         #else
            C[i+j*ldc] = c00;
         #endif
      }
   }
}

#if defined(ALPHA1) && defined(BETA1)
void dgemm(int ta, int tb, int M, int N, int K, double alpha, const double *A,
           int lda, const double *B, int ldb, double beta, double *C, int ldc)
{
#if 1
   if (alpha == 1.0)
   {
      if (beta == 1.0)
         dgemm_a1b1(ta, tb, M, N, K, alpha, A, lda, B, ldb, beta, C, ldc);
      else if (beta == 0.0)
         dgemm_a1b0(ta, tb, M, N, K, alpha, A, lda, B, ldb, beta, C, ldc);
      else
         dgemm_a1bX(ta, tb, M, N, K, alpha, A, lda, B, ldb, beta, C, ldc);
   }
   else
   {
      if (beta == 1.0)
         dgemm_aXb1(ta, tb, M, N, K, alpha, A, lda, B, ldb, beta, C, ldc);
      else if (beta == 0.0)
         dgemm_aXb0(ta, tb, M, N, K, alpha, A, lda, B, ldb, beta, C, ldc);
      else
         dgemm_aXbX(ta, tb, M, N, K, alpha, A, lda, B, ldb, beta, C, ldc);
   }
#else
   int i, j, k;
   register double c00;
   for (j=0; j < N; j++)
   {
      for (i=0; i < M; i++)
      {
         c00 = 0.0;
         for (k=0; k < K; k++)
               c00 += alpha * A[k+i*lda] * B[k+j*ldb];
         if (beta == 0.0)
            C[i+j*ldc] = c00;
         else 
            C[i+j*ldc] = C[i+j*ldc]*beta + c00;
      }
   }
#endif
}
#endif
